### ISSUE TITLE
selectfieldset doesn't work correctly within an array or tabarray.

### ISSUE THREAD

**Issue by cornelius1** [jsonform/jsonform#276]
Similar to issue #44, selectfieldset no longer seems to work as expected within an array or tabarray. The dropdown doesn't affect which fields are shown, and after changing the selection back to its first option, all fields are shown at the same time. With tabarray, all fields are shown from the beginning and selection doesn't affect anything. (I don't have permission to reopen the old issue, so I opened this one.)

Here is a small example to reproduce the issue:
```
{
  "schema": {
    "things": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string",
            "title": "Text"
          },
          "category": {
            "type": "string",
            "title": "Category",
            "enum": [
              "History",
              "Arts",
              "Science"
            ]
          }
        }
      }
    }
  },
  "form": [
    {
      "title": "Things",
      "type": "array",
      "items": {
        "type": "selectfieldset",
        "title": "Make a choice",
        "items": [
          {
            "key": "things[].text",
            "legend": "Search by text"
          },
          {
            "key": "things[].category",
            "legend": "Search by category"
          }
        ]
      }
    }
  ]
}
```

**Comment by tchapi** [comment]
Hello @cornelius1 

This seem indeed to be a bug. I'm looking at it.

**Comment by tchapi** [comment]
Can you try the https://github.com/jsonform/jsonform/tree/bugfix/selectfieldset branch and tell me if that solves the issues you're having ?

**Comment by cornelius1** [comment]
Seems to work with that change. Thanks for the quick fix!

**Comment by cornelius1** [comment]
Spoke too soon. The issue seems to come back (i.e. all fields of a selectfieldset are shown at the same time) after adding more array items using the + button, changing a selectfieldset's selection, and then moving it to a different position in the array via drag-and-drop.

**Comment by tchapi** [comment]
Ok, let me investigate that specific behaviour

**Comment by tchapi** [comment]
Hello again @cornelius1 

I've made some more improvements that I pushed on the same branch (and created the WIP PR https://github.com/jsonform/jsonform/pull/279).

Could you have a look ? Also, could you be so kind as to check also with a `tabarray` instead of a simple `array` (in the `form` definition) for the same kind of buggy behaviour ? I think the fixes address the two.

Thanks for your patience
BR

**Comment by cornelius1** [comment]
Thanks for the improvements! I tried [the version with those fixes](https://github.com/jsonform/jsonform/blob/78787fbba8061ccef82d4ca683e809181b282134/lib/jsonform.js), and it indeed fixes the "all fields appear at the same time" issue. However, I still see two (smaller) issues after adding new item(s) to the array (in the example form above), whether using `array` or `tabarray`:
1. If the Text fields are empty (i.e. no text entered), moving a selectfieldset item via drag-and-drop to a new position causes the selection of the topmost item to change from "Search by text" to "Search by category".
1. If the value of any selectfieldset item (text or enum) has been changed to a non-default value, it reverts to the default value (i.e. empty string for text or the first value for enum) after doing these:
   1. change the selection of the item to another option (e.g. from "Search by text" to "Search by category"),
   1. move the item via drag-and-drop to a new position,
   1. change the selection back to the previous option.

For comparison, (2) does not happen (i.e. the modified value does *not* get lost) when one just moves the item (without changing the selection back and forth) or just changes the selection back and forth (without moving the item in between).

**Comment by tchapi** [comment]
We're getting there ! Thanks for your thorough tests. I probably won't have time to check that until next week, but I'll keep you posted.

BR

**Comment by tchapi** [comment]
Hi,

Ok, so the behaviour is quite "normal" as-is, let me explain why:

a. When using an enum, the first item is automatically selected when the form is created (_this is the way selects work in HTML_). So if you create two items in an `array`, and don't touch anything, and then drag-and-drop the second item to a new position, jsonform will evaluate this item and look for user-inputted values, will find that the first option of the enum is not the default value (because there is no default value), and consider that this is the user that chose it, and so will display the 'Search by category' in this case

b. Your second case boils down to the same problem — when we drag-and-drop, we just keep the current value (either text or category) and discard the other.

So while not being optimal, the behaviour is expected since `selectfieldset` is _not really part of the form_ and only a visual shenanigan to offer alternatives.

I reckon that it'd be great if we can "store" somehow the value of the alternative (i.e. the value of the `selectfieldset`) when drag-and-dropping. **If you have an idea how to do this and can do a PR, that'd be very much welcome !**
